[package]
name = "dijkstra-rust"
version = "0.1.0"
authors = ["Eddie Sheffield <eddie@eddiesheffield.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
